version: "3"
services:
  webservice:
    # replace username/repo:tag with your name and image details
    build: .
    ports:
      - "8080:8080"
    networks:
      - crnet
    environment:
      - DB=dontknowyet
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: 'coordinate_rocks'
      MYSQL_USER: 'cr_service'
      MYSQL_PASSWORD: 'asifimgonnatellyou'
      MYSQL_ROOT_PASSWORD: 'superamazingpasswordsaresuperamazing'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mariadb/coordinate.rocks/
    network:
      crnet
networks:
  crnet:
